name: CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false

      matrix:
        include:
          - runs-on: ubuntu-latest
            os: "android"
          - runs-on: windows-latest
            os: "windows"

    steps:
      - uses: actions/checkout@v4

      - name: Get SSL Version
        shell: bash
        run: echo "SSL_VERSION=$(./tools/openssl-version.sh)" >> $GITHUB_ENV

      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'

      - name: Install wget
        if: runner.os == 'Windows'
        run: choco install wget

      - name: Setup perl
        shell: bash
        if: runner.os == 'Windows'
        run: |
          wget https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54021_64bit_UCRT/strawberry-perl-5.40.2.1-64bit-portable.zip
          mkdir strawberry
          cd strawberry
          7z x ../strawberry-perl-5.40.2.1-64bit-portable.zip

          #  I hate microsoft
          PERL_PATH="/d/a/OpenSSL-CI/OpenSSL-CI/strawberry/perl"
          echo "PERL_BIN=$PERL_PATH/bin" >> $GITHUB_ENV
          echo "PERL5LIB=$PERL_PATH/vendor/lib;$PERL_PATH/lib" >> $GITHUB_ENV

          ls $PERL_PATH/lib

      - name: Build (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          export PATH="$PERL_BIN:$PATH"
          chmod a+x ./${{ matrix.os }}/build.sh
          ./${{ matrix.os }}/build.sh

      - name: Build (Android)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          chmod a+x ./${{ matrix.os }}/build.sh
          ./${{ matrix.os }}/build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: artifacts/*
